
using System;
using System.Collections.Generic;

namespace Oracle
{
    public enum PieceIdentity
    {
        King,
        Prince,
        GoldGeneral,
        RightGeneral,
        RightArmy,
        LeftGeneral,
        LeftArmy,
        RearStandard,
        Queen,
        FreeDreamEater,
        WoodenDove,
        CeramicDove,
        EarthDragon,
        FreeDemon,
        RunningHorse,
        BeastCadet,
        LongNosedGoblin,
        LeftMountainEagle,
        RightMountainEagle,
        FireDemon,
        FreeFire,
        Whale,
        GreatWhale,
        RunningRabbit,
        WhiteTiger,
        DivineTiger,
        TurtleSnake,
        DivineTurtle,
        Lance,
        ReverseChariot,
        FragrantElephant,
        ElephantKing,
        WhiteElephant,
        TurtleDove,
        FlyingSwallow,
        CaptiveOfficer,
        CaptiveBird,
        RainDragon,
        ForestDemon,
        ThunderRunner,
        MountainStag,
        RunningPup,
        FreeLeopard,
        RunningSerpent,
        FreeSerpent,
        SideSerpent,
        GreatShark,
        GreatDove,
        RunningTiger,
        FreeTiger,
        RunningBear,
        FreeBear,
        Yaksha,
        HeavenlyTetrarch,
        BuddhistDevil,
        GuardianOfTheGods,
        Wrestler,
        SilverGeneral,
        DrunkenElephant,
        NeighboringKing,
        GoldChariot,
        PlayfulCockatoo,
        SideDragon,
        RunningDragon,
        RunningStag,
        FreeStag,
        RunningWolf,
        FreeWolf,
        BishopGeneral,
        RainDemon,
        RookGeneral,
        FlyingCrocodile,
        RightTiger,
        LeftTiger,
        RightDragon,
        LeftDragon,
        BeastOfficer,
        BeastBird,
        WindDragon,
        FreeDragon,
        FreePup,
        FreeDog,
        RushingBird,
        OldKite,
        Peacock,
        WaterDragon,
        FireDragon,
        CopperGeneral,
        PhoenixMaster,
        KirinMaster,
        SilverChariot,
        GooseWing,
        VerticalBear,
        Knight,
        PigGeneral,
        FreePig,
        ChickenGeneral,
        FreeChicken,
        PupGeneral,
        HorseGeneral,
        FreeHorse,
        OxGeneral,
        FreeOx,
        CenterStandard,
        SideBoar,
        FreeBoar,
        SilverRabbit,
        GoldenDeer,
        Lion,
        FuriousFiend,
        CaptiveCadet,
        GreatStag,
        ViolentDragon,
        WoodlandDemon,
        RightPhoenix,
        ViceGeneral,
        GreatGeneral,
        StoneChariot,
        WalkingHeron,
        CloudEagle,
        StrongEagle,
        Bishop,
        Rook,
        SideWolf,
        FlyingCat,
        MountainFalcon,
        VerticalTiger,
        Soldier,
        Cavalier,
        LittleStandard,
        CloudDragon,
        CopperChariot,
        CopperElephant,
        RunningChariot,
        BurningChariot,
        RamsHeadSoldier,
        TigerSoldier,
        ViolentOx,
        GreatDragon,
        AncientDragon,
        GoldenBird,
        FreeBird,
        DarkSpirit,
        BuddhistSpirit,
        Deva,
        TeachingKing,
        WoodChariot,
        WindSnappingTurtle,
        WhiteHorse,
        GreatHorse,
        LeftHowlingDog,
        RightHowlingDog,
        RightDog,
        LeftDog,
        SideMover,
        PrancingStag,
        WaterBuffalo,
        GreatDreamEater,
        FerociousLeopard,
        FierceEagle,
        FlyingDragon,
        PoisonousSnake,
        FlyingGoose,
        StruttingCrow,
        FlyingFalcon,
        BlindDog,
        WaterGeneral,
        FireGeneral,
        Phoenix,
        Kirin,
        HookMover,
        LittleTurtle,
        TreasureTurtle,
        GreatTurtle,
        SpiritTurtle,
        Capricorn,
        TileChariot,
        RunningTile,
        VerticalWolf,
        SideOx,
        Donkey,
        FlyingHorse,
        ViolentBear,
        GreatBear,
        AngryBoar,
        EvilWolf,
        VenomousWolf,
        LiberatedHorse,
        HeavenlyHorse,
        FlyingCock,
        RaidingFalcon,
        OldMonkey,
        MountainWitch,
        ChineseCock,
        WizardStork,
        NorthernBarbarian,
        SouthernBarbarian,
        WesternBarbarian,
        EasternBarbarian,
        ViolentStag,
        RushingBoar,
        ViolentWolf,
        BearsEyes,
        TreacherousFox,
        MountainCrane,
        CenterMaster,
        RocMaster,
        EarthChariot,
        YoungBird,
        VermillionSparrow,
        DivineSparrow,
        BlueDragon,
        DivineDragon,
        EnchantedBadger,
        Horseman,
        SwoopingOwl,
        ClimbingMonkey,
        CatSword,
        SwallowsWings,
        GlidingSwallow,
        BlindMonkey,
        FlyingStag,
        BlindTiger,
        OxCart,
        PloddingOx,
        SideFlier,
        BlindBear,
        OldRat,
        BirdOfParadise,
        SquareMover,
        StrongChariot,
        CoiledSerpent,
        CoiledDragon,
        RecliningDragon,
        FreeEagle,
        LionHawk,
        ChariotSoldier,
        HeavenlyTetrarchKing,
        SideSoldier,
        VerticalSoldier,
        WindGeneral,
        ViolentWind,
        RiverGeneral,
        ChineseRiver,
        MountainGeneral,
        PeacefulMountain,
        FrontStandard,
        HorseSoldier,
        WoodGeneral,
        OxSoldier,
        RunningOx,
        EarthGeneral,
        BoarSoldier,
        RunningBoar,
        StoneGeneral,
        LeopardSoldier,
        RunningLeopard,
        TileGeneral,
        BearSoldier,
        StrongBear,
        IronGeneral,
        GreatStandard,
        GreatMaster,
        RightChariot,
        RightIronChariot,
        LeftChariot,
        LeftIronChariot,
        SideMonkey,
        VerticalMover,
        FlyingOx,
        FireOx,
        LongbowSoldier,
        LongbowGeneral,
        VerticalPup,
        LeopardKing,
        VerticalHorse,
        BurningSoldier,
        BurningGeneral,
        DragonHorse,
        DragonKing,
        SwordSoldier,
        SwordGeneral,
        HornedFalcon,
        GreatFalcon,
        SoaringEagle,
        GreatEagle,
        SpearSoldier,
        SpearGeneral,
        VerticalLeopard,
        GreatLeopard,
        SavageTiger,
        GreatTiger,
        CrossbowSoldier,
        CrossbowGeneral,
        RoaringDog,
        LionDog,
        GreatElephant,
        Dog,
        MultiGeneral,
        GoBetween,
        Pawn
    }

    public class Pieces
    {
        private static Dictionary<PieceIdentity, (string Name, string Kanji, string Romanji, PieceIdentity? promotesTo)> _PieceInfo = new Dictionary<PieceIdentity, (string Name, string Kanji, string Romanji, PieceIdentity? promotesTo)>
        {
            { PieceIdentity.King,                   ("King",                    "玉将",     "gyokushō", null) },
            { PieceIdentity.Prince,                 ("Prince",                  "太子",     "taishi",   PieceIdentity.King) },
            { PieceIdentity.GoldGeneral,            ("Gold General",            "金将",     "kinshō",   PieceIdentity.Rook) },
            { PieceIdentity.RightGeneral,           ("Right General",           "右将",     "ushō",     PieceIdentity.RightArmy) },
            { PieceIdentity.RightArmy,              ("Right Army",              "右軍",     "ugun",     null) },
            { PieceIdentity.LeftGeneral,            ("Left General",            "左将",     "sashō",    PieceIdentity.LeftArmy) },
            { PieceIdentity.LeftArmy,               ("Left Army",               "左軍",     "sagun",    null) },
            { PieceIdentity.RearStandard,           ("Rear Standard",           "後旗",     "kōki",     PieceIdentity.CenterStandard) },
            { PieceIdentity.Queen,                  ("Queen",                   "奔王",     "honnō",    PieceIdentity.GreatGeneral) },
            { PieceIdentity.FreeDreamEater,         ("Free Dream-Eater",        "奔獏",     "honbaku",  PieceIdentity.Queen) },
            { PieceIdentity.WoodenDove,             ("Wooden Dove",             "鳩槃",     "kyūhan",   null) },
            { PieceIdentity.CeramicDove,            ("Ceramic Dove",            "鳩盤",     "kyūban",   null) },
            { PieceIdentity.EarthDragon,            ("Earth Dragon",            "地龍",     "chiryū",   PieceIdentity.RainDragon) },
            { PieceIdentity.FreeDemon,              ("Free demon",              "奔鬼",     "honki",    PieceIdentity.Queen) },
            { PieceIdentity.RunningHorse,           ("Running Horse",           "走馬",     "sōma",     PieceIdentity.FreeDemon) },       // a.k.a. romaji: Sōba
            { PieceIdentity.BeastCadet,             ("Beast Cadet",             "獣曹",     "jūsō",     PieceIdentity.BeastOfficer) },
            { PieceIdentity.LongNosedGoblin,        ("Long-nosed Goblin",       "天狗",     "tengu",    null) },
            { PieceIdentity.LeftMountainEagle,      ("Mountain Eagle",          "山鷲",     "sanshū",   PieceIdentity.SoaringEagle) },
            { PieceIdentity.RightMountainEagle,     ("Mountain Eagle",          "山鷲",     "sanshū",   PieceIdentity.SoaringEagle) },
            { PieceIdentity.FireDemon,              ("Fire Demon",              "火鬼",     "kaki",     PieceIdentity.FreeFire) },
            { PieceIdentity.FreeFire,               ("Free Fire",               "奔火",     "honka",    null) },
            { PieceIdentity.Whale,                  ("Whale",                   "鯨鯢",     "keigei",   PieceIdentity.GreatWhale) },
            { PieceIdentity.GreatWhale,             ("Great Whale",             "大鯨",     "daigei",   null) },
            { PieceIdentity.RunningRabbit,          ("Running Rabbit",          "走兎",     "sōto",     PieceIdentity.TreacherousFox) },
            { PieceIdentity.WhiteTiger,             ("White Tiger",             "白虎",     "byakko",   PieceIdentity.DivineTiger) },
            { PieceIdentity.DivineTiger,            ("Divine Tiger",            "神虎",     "shinko",   null) },
            { PieceIdentity.TurtleSnake,            ("Turtle-Snake",            "玄武",     "genbu",    PieceIdentity.DivineTurtle) },
            { PieceIdentity.DivineTurtle,           ("Divine Turtle",           "神亀",     "shinki",   null) },
            { PieceIdentity.Lance,                  ("Lance",                   "香車",     "kyōsha",   PieceIdentity.WhiteHorse) },
            { PieceIdentity.ReverseChariot,         ("Reverse Chariot",         "反車",     "hensha",   PieceIdentity.Whale) },
            { PieceIdentity.FragrantElephant,       ("Fragrant Elephant",       "香象",     "kōzō",     PieceIdentity.ElephantKing) },
            { PieceIdentity.ElephantKing,           ("Elephant King",           "象王",     "zōō",      null) },
            { PieceIdentity.WhiteElephant,          ("White Elephant",          "白象",     "hakuzō",   PieceIdentity.ElephantKing) },
            { PieceIdentity.TurtleDove,             ("Turtle Dove",             "山鳩",     "sankyū",   PieceIdentity.GreatDove) },
            { PieceIdentity.FlyingSwallow,          ("Flying Swallow",          "飛燕",     "hien",     PieceIdentity.Rook) },
            { PieceIdentity.CaptiveOfficer,         ("Captive Officer",         "禽吏",     "kinri",    PieceIdentity.CaptiveBird) },
            { PieceIdentity.CaptiveBird,            ("Captive Bird",            "禽鳥",     "kinchō",   null) },
            { PieceIdentity.RainDragon,             ("Rain Dragon",             "雨龍",     "uryū",     PieceIdentity.GreatDragon) },
            { PieceIdentity.ForestDemon,            ("Forest Demon",            "森鬼",     "shinki",   PieceIdentity.ThunderRunner) },
            { PieceIdentity.ThunderRunner,          ("Thunder Runner",          "雷走",     "raisō",    null) },
            { PieceIdentity.MountainStag,           ("Mountain Stag",           "山鹿",     "sanroku",  PieceIdentity.GreatStag) },
            { PieceIdentity.RunningPup,             ("Running Pup",             "走狗",     "sōku",     PieceIdentity.FreeLeopard) },
            { PieceIdentity.FreeLeopard,            ("Free Leopard",            "奔豹",     "honpyō",   null) },
            { PieceIdentity.RunningSerpent,         ("Running Serpent",         "走蛇",     "sōja",     PieceIdentity.FreeSerpent) },
            { PieceIdentity.FreeSerpent,            ("Free Serpent",            "奔蛇",     "honja",    null) },
            { PieceIdentity.SideSerpent,            ("Side Serpent",            "横蛇",     "ōja",      PieceIdentity.GreatShark) },
            { PieceIdentity.GreatShark,             ("Great Shark",             "大鱗",     "dairin",   null) },
            { PieceIdentity.GreatDove,              ("Great Dove",              "大鳩",     "daikyū",   PieceIdentity.WoodenDove) },
            { PieceIdentity.RunningTiger,           ("Running Tiger",           "走虎",     "sōko",     PieceIdentity.FreeTiger) },
            { PieceIdentity.FreeTiger,              ("Free Tiger",              "奔虎",     "honko",    null) },
            { PieceIdentity.RunningBear,            ("Running Bear",            "走熊",     "sōyū",     PieceIdentity.FreeBear) },
            { PieceIdentity.FreeBear,               ("Free Bear",               "奔熊",     "hon’yū",   null) },
            { PieceIdentity.Yaksha,                 ("Yaksha",                  "夜叉",     "yasha",    PieceIdentity.HeavenlyTetrarch) },
            { PieceIdentity.HeavenlyTetrarch,       ("Heavenly Tetrarch",       "四天",     "shiten",   null) },
            { PieceIdentity.BuddhistDevil,          ("Buddhist Devil",          "羅刹",     "rasetsu",  PieceIdentity.HeavenlyTetrarch) },
            { PieceIdentity.GuardianOfTheGods,      ("Guardian of the Gods",    "金剛",     "kongō",    PieceIdentity.HeavenlyTetrarch) },
            { PieceIdentity.Wrestler,               ("Wrestler",                "力士",     "rikishi",  PieceIdentity.HeavenlyTetrarch) },
            { PieceIdentity.SilverGeneral,          ("Silver General",          "銀将",     "ginshō",   PieceIdentity.VerticalMover) },
            { PieceIdentity.DrunkenElephant,        ("Drunken Elephant",        "酔象",     "suizō",    PieceIdentity.Prince) },
            { PieceIdentity.NeighboringKing,        ("Neighboring King",        "近王",     "kinnō",    PieceIdentity.FrontStandard) },
            { PieceIdentity.GoldChariot,            ("Gold Chariot",            "金車",     "kinsha",   PieceIdentity.PlayfulCockatoo) },
            { PieceIdentity.PlayfulCockatoo,        ("Playful Cockatoo",        "遊䳇",     "yūmo",     null) },
            { PieceIdentity.SideDragon,             ("Side Dragon",             "横龍",     "ōryū",     PieceIdentity.RunningDragon) },
            { PieceIdentity.RunningDragon,          ("Running Dragon",          "走龍",     "sōryū",    null) },
            { PieceIdentity.RunningStag,            ("Running Stag",            "走鹿",     "sōroku",   PieceIdentity.FreeStag) },
            { PieceIdentity.FreeStag,               ("Free Stag",               "奔鹿",     "honroku",  null) },
            { PieceIdentity.RunningWolf,            ("Running Wolf",            "走狼",     "sōrō",     PieceIdentity.FreeWolf) },
            { PieceIdentity.FreeWolf,               ("Free Wolf",               "奔狼",     "honrō",    null) },
            { PieceIdentity.BishopGeneral,          ("Bishop General",          "角将",     "kakushō",  PieceIdentity.RainDemon) },
            { PieceIdentity.RainDemon,              ("Rain Demon",              "霖鬼",     "rinki",    null) },
            { PieceIdentity.RookGeneral,            ("Rook General",            "飛将",     "hishō",    PieceIdentity.FlyingCrocodile) },
            { PieceIdentity.FlyingCrocodile,        ("Flying Crocodile",        "飛鰐",     "higaku",   null) },
            { PieceIdentity.RightTiger,             ("Right Tiger",             "右虎",     "uko",      PieceIdentity.WhiteTiger) },
            { PieceIdentity.LeftTiger,              ("Left Tiger",              "左虎",     "sako",     PieceIdentity.TurtleSnake) },
            { PieceIdentity.RightDragon,            ("Right Dragon",            "右龍",     "uryū",     PieceIdentity.BlueDragon) },
            { PieceIdentity.LeftDragon,             ("Left Dragon",             "左龍",     "saryū",    PieceIdentity.VermillionSparrow) },
            { PieceIdentity.BeastOfficer,           ("Beast Officer",           "獣吏",     "jūri",     PieceIdentity.BeastBird) },
            { PieceIdentity.BeastBird,              ("Beast Bird",              "獣鳥",     "jūchō",    null) },
            { PieceIdentity.WindDragon,             ("Wind Dragon",             "風龍",     "fūryū",    PieceIdentity.FreeDragon) },
            { PieceIdentity.FreeDragon,             ("Free Dragon",             "奔龍",     "honryū",   null) },
            { PieceIdentity.FreePup,                ("Free Pup",                "奔狗",     "honku",    PieceIdentity.FreeDog) },
            { PieceIdentity.FreeDog,                ("Free Dog",                "奔犬",     "honken",   null) },
            { PieceIdentity.RushingBird,            ("Rushing Bird",            "行鳥",     "gyōchō",   PieceIdentity.FreeDemon) },
            { PieceIdentity.OldKite,                ("Old kite",                "古鵄",     "kotetsu",  PieceIdentity.LongNosedGoblin) },
            { PieceIdentity.Peacock,                ("Peacock",                 "孔雀",     "kujaku",   PieceIdentity.LongNosedGoblin) },
            { PieceIdentity.WaterDragon,            ("Water Dragon",            "水龍",     "suiryū",   PieceIdentity.PhoenixMaster) },
            { PieceIdentity.FireDragon,             ("Fire Dragon",             "火龍",     "karyū",    PieceIdentity.KirinMaster) },
            { PieceIdentity.CopperGeneral,          ("Copper General",          "銅将",     "dōshō",    PieceIdentity.SideMover) },
            { PieceIdentity.PhoenixMaster,          ("Phoenix Master",          "鳳師",     "hōshi",    null) },
            { PieceIdentity.KirinMaster,            ("Kirin Master",            "麟師",     "rinshi",   null) },
            { PieceIdentity.SilverChariot,          ("Silver Chariot",          "銀車",     "ginsha",   PieceIdentity.GooseWing) },
            { PieceIdentity.GooseWing,              ("Goose Wing",              "鴻翼",     "kōyoko",   null) },
            { PieceIdentity.VerticalBear,           ("Vertical Bear",           "竪熊",     "shuyū",    PieceIdentity.FreeBear) },
            { PieceIdentity.Knight,                 ("Knight",                  "桂馬",     "keima",    PieceIdentity.SideSoldier) },
            { PieceIdentity.PigGeneral,             ("Pig General",             "豚将",     "tonshō",   PieceIdentity.FreePig) },
            { PieceIdentity.FreePig,                ("Free Pig",                "奔豚",     "honton",   null) },
            { PieceIdentity.ChickenGeneral,         ("Chicken General",         "鶏将",     "keishō",   PieceIdentity.FreeChicken) },
            { PieceIdentity.FreeChicken,            ("Free Chicken",            "奔鶏",     "honkei",   null) },
            { PieceIdentity.PupGeneral,             ("Pup General",             "狗将",     "kushō",    PieceIdentity.FreePup) },
            { PieceIdentity.HorseGeneral,           ("Horse General",           "馬将",     "bashō",    PieceIdentity.FreeHorse) },
            { PieceIdentity.FreeHorse,              ("Free Horse",              "奔馬",     "honba",    null) },
            { PieceIdentity.OxGeneral,              ("Ox General",              "牛将",     "gyūshō",   PieceIdentity.FreeOx) },
            { PieceIdentity.FreeOx,                 ("Free Ox",                 "奔牛",     "hongyū",   null) },
            { PieceIdentity.CenterStandard,         ("Center Standard",         "中旗",     "chūki",    PieceIdentity.FrontStandard) },
            { PieceIdentity.SideBoar,               ("Side Boar",               "横猪",     "ōcho",     PieceIdentity.FreeBoar) },
            { PieceIdentity.FreeBoar,               ("Free Boar",               "奔猪",     "honcho",   null) },
            { PieceIdentity.SilverRabbit,           ("Silver Rabbit",           "銀兎",     "ginto",    PieceIdentity.Whale) },
            { PieceIdentity.GoldenDeer,             ("Golden Deer",             "金鹿",     "konroku",  PieceIdentity.WhiteHorse) },
            { PieceIdentity.Lion,                   ("Lion",                    "獅子",     "shishi",   PieceIdentity.FuriousFiend) },
            { PieceIdentity.FuriousFiend,           ("Furious Fiend",           "奮迅",     "funjin",   null) },
            { PieceIdentity.CaptiveCadet,           ("Captive Cadet",           "禽曹",     "kinsō",    PieceIdentity.CaptiveOfficer) },
            { PieceIdentity.GreatStag,              ("Great Stag",              "大鹿",     "dairoku",  PieceIdentity.FreeStag) },
            { PieceIdentity.ViolentDragon,          ("Violent Dragon",          "猛龍",     "mōryū",    PieceIdentity.GreatDragon) },
            { PieceIdentity.WoodlandDemon,          ("Woodland Demon",          "林鬼",     "rinki",    PieceIdentity.RightPhoenix) },
            { PieceIdentity.RightPhoenix,           ("Right Phoenix",           "右鵰",     "ushū",     null) },
            { PieceIdentity.ViceGeneral,            ("Vice General",            "副将",     "fukushō",  PieceIdentity.GreatGeneral) },
            { PieceIdentity.GreatGeneral,           ("Great General",           "大将",     "taishō",   null) },
            { PieceIdentity.StoneChariot,           ("Stone Chariot",           "石車",     "sekisha",  PieceIdentity.WalkingHeron) },
            { PieceIdentity.WalkingHeron,           ("Walking Heron",           "歩䳲",     "fushin",   null) },
            { PieceIdentity.CloudEagle,             ("Cloud Eagle",             "雲鷲",     "unjū",     PieceIdentity.StrongEagle) },
            { PieceIdentity.StrongEagle,            ("Strong Eagle",            "勁鷲",     "keijū",    null) },
            { PieceIdentity.Bishop,                 ("Bishop",                  "角行",     "kakugyō",  PieceIdentity.DragonHorse) },
            { PieceIdentity.Rook,                   ("Rook",                    "飛車",     "hisha",    PieceIdentity.DragonKing) },
            { PieceIdentity.SideWolf,               ("Side Wolf",               "横狼",     "ōrō",      PieceIdentity.FreeWolf) },
            { PieceIdentity.FlyingCat,              ("Flying Cat",              "飛猫",     "hibyō",    PieceIdentity.Rook) },
            { PieceIdentity.MountainFalcon,         ("Mountain Falcon",         "山鷹",     "san’ō",    PieceIdentity.HornedFalcon) },
            { PieceIdentity.VerticalTiger,          ("Vertical Tiger",          "竪虎",     "shuko",    PieceIdentity.FreeTiger) },
            { PieceIdentity.Soldier,                ("Soldier",                 "兵士",     "heishi",   PieceIdentity.Cavalier) },
            { PieceIdentity.Cavalier,               ("Cavalier",                "騎士",     "kishi",    null) },
            { PieceIdentity.LittleStandard,         ("Little Standard",         "小旗",     "shōki",    PieceIdentity.RearStandard) },
            { PieceIdentity.CloudDragon,            ("Cloud Dragon",            "雲龍",     "unryū",    PieceIdentity.GreatDragon) },
            { PieceIdentity.CopperChariot,          ("Copper Chariot",          "銅車",     "dōsha",    PieceIdentity.CopperElephant) },
            { PieceIdentity.CopperElephant,         ("Copper Elephant",         "銅象",     "dōzō",     null) },
            { PieceIdentity.RunningChariot,         ("Running Chariot",         "走車",     "sōsha",    PieceIdentity.BurningChariot) },
            { PieceIdentity.BurningChariot,         ("Burning Chariot",         "炮車",     "hōsha",    null) },
            { PieceIdentity.RamsHeadSoldier,        ("Ram's Head Soldier",      "羊兵",     "yōhei",    PieceIdentity.TigerSoldier) },
            { PieceIdentity.TigerSoldier,           ("Tiger Soldier",           "虎兵",     "kohei",    null) },
            { PieceIdentity.ViolentOx,              ("Violent Ox",              "猛牛",     "mōgyū",    PieceIdentity.FlyingOx) },
            { PieceIdentity.GreatDragon,            ("Great Dragon",            "大龍",     "dairyū",   PieceIdentity.AncientDragon) },
            { PieceIdentity.AncientDragon,          ("Ancient Dragon",          "元龍",     "genryū",   null) },                              // a.k.a.  Romanji: Ganryū
            { PieceIdentity.GoldenBird,             ("Golden Bird",             "金翅",     "kinshi",   PieceIdentity.FreeBird) },
            { PieceIdentity.FreeBird,               ("Free Bird",               "奔翅",     "honshi",   null) },
            { PieceIdentity.DarkSpirit,             ("Dark Spirit",             "無明",     "mumyō",    PieceIdentity.BuddhistSpirit) },
            { PieceIdentity.BuddhistSpirit,         ("Buddhist Spirit",         "法性",     "hōsei",    null) },
            { PieceIdentity.Deva,                   ("Deva",                    "提婆",     "daiba",    PieceIdentity.TeachingKing) },
            { PieceIdentity.TeachingKing,           ("Teaching King",           "教王",     "kyōō",     null) },
            { PieceIdentity.WoodChariot,            ("Wood Chariot",            "木車",     "mokusha",  PieceIdentity.WindSnappingTurtle) },
            { PieceIdentity.WindSnappingTurtle,     ("Wind Snapping Turtle",    "風鼈",     "fūbetsu",  null) },
            { PieceIdentity.WhiteHorse,             ("White Horse",             "白駒",     "hakku",    PieceIdentity.GreatHorse) },
            { PieceIdentity.GreatHorse,             ("Great Horse",             "大駒",     "daiku",    null) },
            { PieceIdentity.LeftHowlingDog,         ("Howling Dog",             "𠵇犬",     "kiken",    PieceIdentity.LeftDog) },
            { PieceIdentity.RightHowlingDog,        ("Howling Dog",             "𠵇犬",     "kiken",    PieceIdentity.LeftDog) },
            { PieceIdentity.RightDog,               ("Right Dog",               "右犬",     "uken",     null) },
            { PieceIdentity.LeftDog,                ("Left Dog",                "左犬",     "saken",    null) },
            { PieceIdentity.SideMover,              ("Side Mover",              "横行",     "ōgyō",     PieceIdentity.FreeBoar) },
            { PieceIdentity.PrancingStag,           ("Prancing Stag",           "踊鹿",     "yōroku",   PieceIdentity.SquareMover) },
            { PieceIdentity.WaterBuffalo,           ("Water Buffalo",           "水牛",     "suigyū",   PieceIdentity.GreatDreamEater) },
            { PieceIdentity.GreatDreamEater,        ("Great Dream-Eater",       "大獏",     "daibaku",  null) },
            { PieceIdentity.FerociousLeopard,       ("Ferocious Leopard",       "猛豹",     "mōhyō",    PieceIdentity.Bishop) },
            { PieceIdentity.FierceEagle,            ("Fierce Eagle",            "猛鷲",     "mōjū",     PieceIdentity.SoaringEagle) },
            { PieceIdentity.FlyingDragon,           ("Flying Dragon",           "飛龍",     "hiryū",    PieceIdentity.DragonKing) },
            { PieceIdentity.PoisonousSnake,         ("Poisonous Snake",         "毒蛇",     "dokuja",   PieceIdentity.HookMover) },
            { PieceIdentity.FlyingGoose,            ("Flying Goose",            "鳫飛",     "ganhi",    PieceIdentity.SwallowsWings) },
            { PieceIdentity.StruttingCrow,          ("Strutting Crow",          "烏行",     "ukō",      PieceIdentity.FlyingFalcon) },
            { PieceIdentity.FlyingFalcon,           ("Flying Falcon",           "飛鷹",     "hiyō",     null) },
            { PieceIdentity.BlindDog,               ("Blind Dog",               "盲犬",     "mōken",    PieceIdentity.ViolentStag) },
            { PieceIdentity.WaterGeneral,           ("Water General",           "水将",     "suishō",   PieceIdentity.ViceGeneral) },
            { PieceIdentity.FireGeneral,            ("Fire General",            "火将",     "kashō",    PieceIdentity.GreatGeneral) },
            { PieceIdentity.Phoenix,                ("Phoenix",                 "鳳凰",     "hōō",      PieceIdentity.GoldenBird) },
            { PieceIdentity.Kirin,                  ("Kirin",                   "麒麟",     "kirin",    PieceIdentity.GoldenBird) },
            { PieceIdentity.HookMover,              ("Hook Mover",              "鉤行",     "kōgyō",    null) },
            { PieceIdentity.LittleTurtle,           ("Little Turtle",           "小亀",     "shōki",    PieceIdentity.TreasureTurtle) },
            { PieceIdentity.TreasureTurtle,         ("Treasure Turtle",         "宝亀",     "hōki",     null) },
            { PieceIdentity.GreatTurtle,            ("Great Turtle",            "大亀",     "daiki",    PieceIdentity.SpiritTurtle) },
            { PieceIdentity.SpiritTurtle,           ("Spirit Turtle",           "霊亀",     "reiki",    null) },
            { PieceIdentity.Capricorn,              ("Capricorn",               "摩羯",     "makatsu",  PieceIdentity.HookMover) },
            { PieceIdentity.TileChariot,            ("Tile Chariot",            "瓦車",     "gasha",    PieceIdentity.RunningTile) },
            { PieceIdentity.RunningTile,            ("Running Tile",            "走瓦",     "sōga",     null) },
            { PieceIdentity.VerticalWolf,           ("Vertical Wolf",           "竪狼",     "shurō",    PieceIdentity.RunningWolf) },
            { PieceIdentity.SideOx,                 ("Side Ox",                 "横牛",     "ōgyū",     PieceIdentity.FlyingOx) },
            { PieceIdentity.Donkey,                 ("Donkey",                  "驢馬",     "roba",     PieceIdentity.CeramicDove) },
            { PieceIdentity.FlyingHorse,            ("Flying Horse",            "馬麟",     "barin",    PieceIdentity.Queen) },
            { PieceIdentity.ViolentBear,            ("Violent Bear",            "猛熊",     "mōyū",     PieceIdentity.GreatBear) },
            { PieceIdentity.GreatBear,              ("Great Bear",              "大熊",     "daiyū",    null) },
            { PieceIdentity.AngryBoar,              ("Angry Boar",              "嗔猪",     "shincho",  PieceIdentity.FreeBoar) },
            { PieceIdentity.EvilWolf,               ("Evil Wolf",               "悪狼",     "akurō",    PieceIdentity.VenomousWolf) },
            { PieceIdentity.VenomousWolf,           ("Venomous Wolf",           "毒狼",     "dokurō",   null) },
            { PieceIdentity.LiberatedHorse,         ("Liberated Horse",         "風馬",     "fūma",     PieceIdentity.HeavenlyHorse) },
            { PieceIdentity.HeavenlyHorse,          ("Heavenly Horse",          "天馬",     "temma",    null) },
            { PieceIdentity.FlyingCock,             ("Flying Cock",             "鶏飛",     "keihi",    PieceIdentity.RaidingFalcon) },
            { PieceIdentity.RaidingFalcon,          ("Raiding Falcon",          "延鷹",     "en’yō",    null) },
            { PieceIdentity.OldMonkey,              ("Old Monkey",              "古猿",     "koen",     PieceIdentity.MountainWitch) },
            { PieceIdentity.MountainWitch,          ("Mountain Witch",          "山母",     "sanbo",    null) },
            { PieceIdentity.ChineseCock,            ("Chinese Cock",            "淮鶏",     "waikei",   PieceIdentity.WizardStork) },
            { PieceIdentity.WizardStork,            ("Wizard Stork",            "仙鷦",     "senkaku",  null) },                            // Kanji should be: 仙·⿱而鷦
            { PieceIdentity.NorthernBarbarian,      ("Northern Barbarian",      "北狄",     "hokuteki", PieceIdentity.WoodenDove) },
            { PieceIdentity.SouthernBarbarian,      ("Southern Barbarian",      "南蛮",     "nanban",   PieceIdentity.GoldenBird) },
            { PieceIdentity.WesternBarbarian,       ("Western Barbarian",       "西戎",     "seijū",    PieceIdentity.LionDog) },
            { PieceIdentity.EasternBarbarian,       ("Eastern Barbarian",       "東夷",     "tōi",      PieceIdentity.Lion) },
            { PieceIdentity.ViolentStag,            ("Violent Stag",            "猛鹿",     "mōroku",   PieceIdentity.RushingBoar) },
            { PieceIdentity.RushingBoar,            ("Rushing Boar",            "行猪",     "gyōcho",   null) },
            { PieceIdentity.ViolentWolf,            ("Violent Wolf",            "猛狼",     "mōrō",     PieceIdentity.BearsEyes) },
            { PieceIdentity.BearsEyes,              ("Bear's Eyes",             "熊眼",     "yūgan",    null) },
            { PieceIdentity.TreacherousFox,         ("Treacherous Fox",         "隠狐",     "inko",     PieceIdentity.MountainCrane) },     // a.k.a.Romanji: Onko
            { PieceIdentity.MountainCrane,          ("Mountain Crane",          "山鶻",     "sankotsu", null) },
            { PieceIdentity.CenterMaster,           ("Center Master",           "中師",     "chūshi",   null) },
            { PieceIdentity.RocMaster,              ("Roc Master",              "鵬師",     "hōshi",    null) },
            { PieceIdentity.EarthChariot,           ("Earth Chariot",           "土車",     "dosha",    PieceIdentity.YoungBird) },
            { PieceIdentity.YoungBird,              ("Young Bird",              "𦬨鳥",     "shakuchō", null) },
            { PieceIdentity.VermillionSparrow,      ("Vermillion Sparrow",      "朱雀",     "suzaku",   PieceIdentity.DivineSparrow) },
            { PieceIdentity.DivineSparrow,          ("Divine Sparrow",          "神雀",     "shinjaku", null) },
            { PieceIdentity.BlueDragon,             ("Blue Dragon",             "青龍",     "seiryū",   PieceIdentity.DivineDragon) },
            { PieceIdentity.DivineDragon,           ("Divine Dragon",           "神龍",     "shinryū",  null) },
            { PieceIdentity.EnchantedBadger,        ("Enchanted Badger",        "変狸",     "henri",    PieceIdentity.CeramicDove) },
            { PieceIdentity.Horseman,               ("Horseman",                "騎兵",     "kihei",    PieceIdentity.Cavalier) },
            { PieceIdentity.SwoopingOwl,            ("Swooping Owl",            "鴟行",     "shigyō",   PieceIdentity.CloudEagle) },
            { PieceIdentity.ClimbingMonkey,         ("Climbing Monkey",         "登猿",     "tōen",     PieceIdentity.ViolentStag) },
            { PieceIdentity.CatSword,               ("Cat Sword",               "猫刄",     "myōjin",   PieceIdentity.DragonHorse) },
            { PieceIdentity.SwallowsWings,          ("Swallow's Wings",         "燕羽",     "en’u",     PieceIdentity.GlidingSwallow) },
            { PieceIdentity.GlidingSwallow,         ("Gliding Swallow",         "燕行",     "engyō",    null) },
            { PieceIdentity.BlindMonkey,            ("Blind Monkey",            "盲猿",     "mōen",     PieceIdentity.FlyingStag) },
            { PieceIdentity.FlyingStag,             ("Flying Stag",             "飛鹿",     "hiroku",   null) },
            { PieceIdentity.BlindTiger,             ("Blind Tiger",             "盲虎",     "mōko",     PieceIdentity.FlyingStag) },
            { PieceIdentity.OxCart,                 ("Oxcart",                  "牛車",     "gissha",   PieceIdentity.PloddingOx) },
            { PieceIdentity.PloddingOx,             ("Plodding Ox",             "歬牛",     "sengyū",   null) },
            { PieceIdentity.SideFlier,              ("Side Flier",              "横飛",     "ōhi",      PieceIdentity.SideDragon) },
            { PieceIdentity.BlindBear,              ("Blind Bear",              "盲熊",     "mōyū",     PieceIdentity.FlyingStag) },
            { PieceIdentity.OldRat,                 ("Old Rat",                 "老鼠",     "rōso",     PieceIdentity.BirdOfParadise) },
            { PieceIdentity.BirdOfParadise,         ("Bird of Paradise",        "古鳥",     "jichō",    null) },                              // Kanji should be: ⿰古寺·⿱時鳥 or ⿰舌寺·⿱時.
            { PieceIdentity.SquareMover,            ("Square Mover",            "方行",     "hōgyō",    PieceIdentity.StrongChariot) },
            { PieceIdentity.StrongChariot,          ("Strong Chariot",          "強車",     "kyōsha",   null) },
            { PieceIdentity.CoiledSerpent,          ("Coiled Serpent",          "蟠蛇",     "banja",    PieceIdentity.CoiledDragon) },
            { PieceIdentity.CoiledDragon,           ("Coiled Dragon",           "蟠龍",     "banryū",   null) },
            { PieceIdentity.RecliningDragon,        ("Reclining Dragon",        "臥龍",     "garyū",    PieceIdentity.GreatDragon) },
            { PieceIdentity.FreeEagle,              ("Free Eagle",              "奔鷲",     "honjū",    null) },
            { PieceIdentity.LionHawk,               ("Lion Hawk",               "獅鷹",     "shiō",     null) },
            { PieceIdentity.ChariotSoldier,         ("Chariot Soldier",         "車兵",     "shahei",   PieceIdentity.HeavenlyTetrarchKing) },
            { PieceIdentity.HeavenlyTetrarchKing,   ("Heavenly Tetrarch King",  "四天",     "shitennō", null) },
            { PieceIdentity.SideSoldier,            ("Side Soldier",            "横兵",     "ōhei",     PieceIdentity.WaterBuffalo) },
            { PieceIdentity.VerticalSoldier,        ("Vertical Soldier",        "竪兵",     "shuhei",   PieceIdentity.ChariotSoldier) },
            { PieceIdentity.WindGeneral,            ("Wind General",            "風将",     "fūshō",    PieceIdentity.ViolentWind) },
            { PieceIdentity.ViolentWind,            ("Violent Wind",            "暴風",     "bōfū",     null) },
            { PieceIdentity.RiverGeneral,           ("River General",           "川将",     "senshō",   PieceIdentity.ChineseRiver) },
            { PieceIdentity.ChineseRiver,           ("Chinese River",           "淮川",     "waisen",   null) },
            { PieceIdentity.MountainGeneral,        ("Mountain General",        "山将",     "sanshō",   PieceIdentity.PeacefulMountain) },
            { PieceIdentity.PeacefulMountain,       ("Peaceful Mountain",       "泰山",     "taizan",   null) },
            { PieceIdentity.FrontStandard,          ("Front Standard",          "前旗",     "zenki",    PieceIdentity.GreatStandard) },
            { PieceIdentity.HorseSoldier,           ("Horse Soldier",           "馬兵",     "bahei",    PieceIdentity.RunningHorse) },
            { PieceIdentity.WoodGeneral,            ("Wood General",            "木将",     "mokushō",  PieceIdentity.WhiteElephant) },
            { PieceIdentity.OxSoldier,              ("Ox Soldier",              "牛兵",     "gyūhei",   PieceIdentity.RunningOx) },
            { PieceIdentity.RunningOx,              ("Running Ox",              "走牛",     "sōgyū",    null) },
            { PieceIdentity.EarthGeneral,           ("Earth General",           "土将",     "doshō",    PieceIdentity.WhiteElephant) },
            { PieceIdentity.BoarSoldier,            ("Boar Soldier",            "猪兵",     "chohei",   PieceIdentity.RunningBoar) },
            { PieceIdentity.RunningBoar,            ("Running Boar",            "走猪",     "sōcho",    null) },
            { PieceIdentity.StoneGeneral,           ("Stone General",           "石将",     "sekishō",  PieceIdentity.WhiteElephant) },
            { PieceIdentity.LeopardSoldier,         ("Leopard Soldier",         "豹兵",     "hyōhei",   PieceIdentity.RunningLeopard) },
            { PieceIdentity.RunningLeopard,         ("Running Leopard",         "走豹",     "sōhyō",    null) },
            { PieceIdentity.TileGeneral,            ("Tile General",            "瓦将",     "gashō",    PieceIdentity.WhiteElephant) },
            { PieceIdentity.BearSoldier,            ("Bear Soldier",            "熊兵",     "yūhei",    PieceIdentity.StrongBear) },
            { PieceIdentity.StrongBear,             ("Strong Bear",             "強熊",     "kyōyū",    null) },
            { PieceIdentity.IronGeneral,            ("Iron General",            "鉄将",     "tesshō",   PieceIdentity.WhiteElephant) },
            { PieceIdentity.GreatStandard,          ("Great Standard",          "大旗",     "daiki",    null) },
            { PieceIdentity.GreatMaster,            ("Great Master",            "大師",     "daishi",   null) },
            { PieceIdentity.RightChariot,           ("Right Chariot",           "右車",     "usha",     PieceIdentity.RightIronChariot) },
            { PieceIdentity.RightIronChariot,       ("Right Iron Chariot",      "右鉄車",   "utessha",  null) },
            { PieceIdentity.LeftChariot,            ("Left Chariot",            "左車",     "sasha",    PieceIdentity.LeftIronChariot) },
            { PieceIdentity.LeftIronChariot,        ("Left Iron Chariot",       "左鉄車",   "satessha", null) },
            { PieceIdentity.SideMonkey,             ("Side Monkey",             "横猿",     "ōen",      PieceIdentity.SideSoldier) },
            { PieceIdentity.VerticalMover,          ("Vertical Mover",          "竪行",     "shugyō",   PieceIdentity.FlyingOx) },
            { PieceIdentity.FlyingOx,               ("Flying Ox",               "飛牛",     "higyū",    PieceIdentity.FireOx) },
            { PieceIdentity.FireOx,                 ("Fire Ox",                 "火牛",     "kagyū",    null) },
            { PieceIdentity.LongbowSoldier,         ("Longbow Soldier",         "弩兵",     "dohei",    PieceIdentity.LongbowGeneral) },
            { PieceIdentity.LongbowGeneral,         ("Longbow General",         "弩将",     "doshō",    null) },
            { PieceIdentity.VerticalPup,            ("Vertical Pup",            "竪狗",     "shuku",    PieceIdentity.LeopardKing) },
            { PieceIdentity.LeopardKing,            ("Leopard King",            "豹王",     "hyōō",     null) },
            { PieceIdentity.VerticalHorse,          ("Vertical Horse",          "竪馬",     "shuba",    PieceIdentity.DragonHorse) },
            { PieceIdentity.BurningSoldier,         ("Burning Soldier",         "炮兵",     "hōhei",    PieceIdentity.BurningGeneral) },
            { PieceIdentity.BurningGeneral,         ("Burning General",         "炮将",     "hōshō",    null) },
            { PieceIdentity.DragonHorse,            ("Dragon Horse",            "龍馬",     "ryūme",    PieceIdentity.HornedFalcon) },
            { PieceIdentity.DragonKing,             ("Dragon King",             "龍王",     "ryūō",     PieceIdentity.SoaringEagle) },
            { PieceIdentity.SwordSoldier,           ("Sword Soldier",           "刀兵",     "tōhei",    PieceIdentity.SwordGeneral) },
            { PieceIdentity.SwordGeneral,           ("Sword General",           "刀将",     "tōshō",    null) },
            { PieceIdentity.HornedFalcon,           ("Horned Falcon",           "角鷹",     "kakuō",    PieceIdentity.GreatFalcon) },
            { PieceIdentity.GreatFalcon,            ("Great Falcon",            "大鷹",     "daiō",     null) },
            { PieceIdentity.SoaringEagle,           ("Soaring Eagle",           "飛鷲",     "hijū",     PieceIdentity.GreatEagle) },
            { PieceIdentity.GreatEagle,             ("Great Eagle",             "大鷲",     "daijū",    null) },
            { PieceIdentity.SpearSoldier,           ("Spear Soldier",           "鎗兵",     "sōhei",    PieceIdentity.SpearGeneral) },
            { PieceIdentity.SpearGeneral,           ("Spear General",           "鎗将",     "sōshō",    null) },
            { PieceIdentity.VerticalLeopard,        ("Vertical Leopard",        "竪豹",     "shuhyō",   PieceIdentity.GreatLeopard) },
            { PieceIdentity.GreatLeopard,           ("Great Leopard",           "大豹",     "daihyō",   null) },
            { PieceIdentity.SavageTiger,            ("Savage Tiger",            "猛虎",     "mōko",     PieceIdentity.GreatTiger) },
            { PieceIdentity.GreatTiger,             ("Great Tiger",             "大虎",     "daiko",    null) },
            { PieceIdentity.CrossbowSoldier,        ("Cross-bow Soldier",       "弓兵",     "kyūhei",   PieceIdentity.CrossbowGeneral) },
            { PieceIdentity.CrossbowGeneral,        ("Cross-bow General",       "弓将",     "kyūshō",   null) },
            { PieceIdentity.RoaringDog,             ("Roaring Dog",             "吼犬",     "kōken",    PieceIdentity.LionDog) },
            { PieceIdentity.LionDog,                ("Lion Dog",                "狛犬",     "komainu",  PieceIdentity.GreatElephant) },
            { PieceIdentity.GreatElephant,          ("Great Elephant",          "大象",     "taizō",    null) },
            { PieceIdentity.Dog,                    ("Dog",                     "犬",       "inu",      PieceIdentity.MultiGeneral) },
            { PieceIdentity.MultiGeneral,           ("Multi General",           "雜将",     "suishō",   null) },
            { PieceIdentity.GoBetween,              ("Go Between",              "仲人",     "chūnin",   PieceIdentity.DrunkenElephant )},
            { PieceIdentity.Pawn,                   ("Pawn",                    "歩兵",     "fuhyō",    PieceIdentity.GoldGeneral) },
        };


        public static string Name(PieceIdentity id) => _PieceInfo[id].Name;

        public static string Kanji(PieceIdentity id) => _PieceInfo[id].Kanji;

        public static string Romanji(PieceIdentity id) => _PieceInfo[id].Romanji;

        public static PieceIdentity? PromotesTo(PieceIdentity id) => _PieceInfo[id].promotesTo;
    }
}